\header {
                title = "Composition Generated by Genetic Algorithm"
                composer = "Mr. GA"
            }
\score {
\fixed c' {
\key fis \major
b' g a' fis' e e4 a' b g d b d e a' c b g c' d' g g4 c b r e' d' e d c fis b r g c a b b g a' fis e g' c c' e a' 
}
\midi{ }
}