\header {
                title = "Composition Generated by Genetic Algorithm"
                composer = "Mr. GA"
            }
\fixed c' {
d' e' a' e' c a c a a' a c g a r r a d' b' r a f c' e e2 d' b d d' e a e' d g c c2 c' e g' g g2 d' b g' b 
}